backend:
  name: github
  repo: wangsongiam/songwang.io 
  branch: master 

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "public"

collections:
  - name: "blog"
    folder: "src/pages/blog"
    label: "Blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    create: true
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 30 characters and less than 160"]}
      - {label: "Description", name: "description", widget: "text", pattern: [".{30,160}", "Should have more than 30 characters and less than 160"]}
      # - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Text", name: "date", widget: "string", default: ""}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string", default: "Song Wang"}
      # - {label: "Featured Image", name: "image", widget: "image", required: false}
      # - {label: "Publish Date", name: "publishdate", widget: "string"}
