backend:
  name: github
  repo: wangsongiam/songwang.io 
  branch: master 

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "public"

collections:
  - name: "blog"
    folder: "src/pages/blog"
    label: "Blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string", default: ""}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "til"
    folder: "src/pages/til"
    label: "TIL"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string", default: ""}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "links"
    folder: "src/pages/links"
    label: "Links"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string", default: ""}
      - {label: "Date", name: "date", widget: "string", default: ""}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "about"
    folder: "src/pages/about"
    label: "About"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "hire"
    folder: "src/pages/hire"
    label: "Hire"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}
